### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lijinke666** [lijinke666/react-music-player#290]
- [x] Optimize bundle size
![image](https://user-images.githubusercontent.com/21015895/106871784-92cbd600-670d-11eb-90c1-61f734cf36ec.png)
- [x] Remove react-darg-list, use sortablejs for support mobile sort audio list  #223 
- [x] optimize async .play() https://developers.google.com/web/updates/2017/06/play-request-was-interrupted
- [x] Mobile issues #287 #289 
- [ ] Use https://github.com/carloscuesta/gitmoji-cli for pretty commit msg
- [ ] Refactor by Typescript + React Hooks 
- [ ] Support React 17
- [ ] Optimize api
